# Generated by Django 5.1.5 on 2025-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakemodel',
            name='flavour',
            field=models.ManyToManyField(blank=True, related_name='flavour', to='main.flavour'),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
